using System.ComponentModel;

namespace KadOzenka.Dal.Enum
{
    public enum ParamNameEnum
    {
        [Description("kn")]
        Kn,
        [Description("date")]
        Date,
        [Description("square")]
        Square,
        [Description("kc")]
        Kc,
        [Description("adres")]
        Adres,
        [Description("name_center")]
        NameCenter,
        [Description("stat_dgi")]
        StatDgi,
        [Description("owner")]
        Owner,
        [Description("typeobj")]
        TypeObj,
        [Description("id_otchet")]
        IdReport,
        [Description("rs")]
        Rs,
        [Description("uprs")]
        Uprs,
        [Description("use")]
        Use,
        [Description("descr")]
        Descr,
        [Description("number")]
        Number,
        [Description("date")]
        ReportDate,
        [Description("id_org")]
        Org,
        [Description("id_fio")]
        Fio,
        [Description("id_sro")]
        Sro,
        [Description("date_in")]
        DateIn,
        [Description("jalob")]
        Claim,
        [Description("name")]
        Name,
        [Description("sud_date")]
        SudDate,
        [Description("status")]
        Status,
        [Description("id_sud")]
        SudId,
        [Description("rec_date")]
        RecDate,
        [Description("rec_user")]
        RecUser,
        [Description("rec_letter")]
        RecLetter,
        [Description("rec_before")]
        RecBefore,
        [Description("rec_after")]
        RecAfter,
        [Description("rec_soglas")]
        RecSoglas,
        [Description("id_zak")]
        IdConclusion,
        [Description("applicanttype")]
		ApplicantType,
		[Description("typeofownership")]
		TypeOfOwnership,
		[Description("exception")]
		IsException,
		[Description("additional_analysis")]
		AdditionalAnalysisRequired,
		[Description("is_satisfied")]
		IsSatisfied,
		[Description("archive_number")]
		ArchiveNumber,
		[Description("appeal_number")]
		AppealNumber

	}
}