version: "3"
services:
  postgres: 
    build: 
      context: .
      dockerfile: services/postgresql/Dockerfile-uat
    container_name: miomo_kadozenka_uat_postgres
    command: postgres -c 'max_connections=200'
    restart: always
    volumes:
      - miomo_kadozenka_postgres_uat:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=miomo_uat
      - POSTGRES_USER=postgres
    ports:
      - 5445:5432
  pgadmin4:
    image: dpage/pgadmin4
    container_name: miomo_kadozenka_uat_pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@genix.pro"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "8032:80"
    volumes:
      - miomo_kadozenka_pgadmin4_uat:/var/lib/pgadmin
volumes:
  miomo_kadozenka_postgres_uat:
  miomo_kadozenka_pgadmin4_uat: