version: "3"
services:
  postgres: 
    build: 
      context: .
      dockerfile: services\postgresql\Dockerfile
    container_name: miomo_kadozenka_uat_postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=miomo_uat
      - POSTGRES_USER=postgres
    ports:
      - 5444:5432
  pgadmin4:
    image: dpage/pgadmin4
    container_name: miomo_kadozenka_uat_pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@genix.pro"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "8032:80"
    volumes:
      - pgadmin4:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin4: