version: "3"
services:
  postgres: 
    build:
      context: .
      dockerfile: services/postgresql/Dockerfile
    container_name: miomo_kadozenka_dev_postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=miomo_dev
      - POSTGRES_USER=postgres
    ports:
      - 5440:5432
  pgadmin4:
    image: dpage/pgadmin4
    container_name: miomo_kadozenka_dev_pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@genix.pro"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "8040:80"
    volumes:
      - pgadmin4:/var/lib/pgadmin
volumes:
  postgres:
  pgadmin4: