version: "3"
services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@genix.pro"
      PGADMIN_DEFAULT_PASSWORD: "123456"
    ports:
      - "8032:80"
    volumes:
      - pgadmin4:/var/lib/pgadmin
volumes:
    pgadmin4: 