SELECT ID FROM KO_TASK
WHERE KO_TASK.ID IN (
        SELECT KO_UNIT.TASK_ID
        FROM KO_UNIT
        WHERE
                (KO_UNIT.PROPERTY_TYPE_CODE <> 4 OR KO_UNIT.PROPERTY_TYPE_CODE IS NULL) AND
                (KO_UNIT.PROPERTY_TYPE_CODE <> 0 OR KO_UNIT.PROPERTY_TYPE_CODE IS NULL)
        ) AND
        TOUR_ID={0} AND
        NOTE_TYPE_CODE=4
ORDER BY KO_TASK.CREATION_DATE DESC;