insert into core_long_process_type ("id", "process_name", "class_name", "schedule_type", "repeat_interval", "enabled", "run_count", "failure_count", "last_start_date", "last_run_duration", "next_run_date", "parameters", "description", "test_result", "parameters_setter_url") values
(14, 'HarmonizationCodProcess', 'KadOzenka.Dal.LongProcess.HarmonizationCodProcess, KadOzenka.Dal', 0, NULL, 1, NULL, NULL, TO_TIMESTAMP('2021.03.02 10:27:29', 'YYYY.MM.DD HH24:MI:SS'), NULL, NULL, NULL, 'Операция гармонизации с использованием справочника ЦОД', 1, NULL)
on conflict (id) do update set "process_name"='HarmonizationCodProcess', "class_name"='KadOzenka.Dal.LongProcess.HarmonizationCodProcess, KadOzenka.Dal', "schedule_type"=0, "repeat_interval"=NULL, "enabled"=1, "run_count"=NULL, "failure_count"=NULL, "last_start_date"=TO_TIMESTAMP('2021.03.02 10:27:29', 'YYYY.MM.DD HH24:MI:SS'), "last_run_duration"=NULL, "next_run_date"=NULL, "parameters"=NULL, "description"='Операция гармонизации с использованием справочника ЦОД', "test_result"=1, "parameters_setter_url"=NULL;

update core_reference
set simple_values = (
    with sel as (select jsonb_array_elements(regexp_replace(simple_values, ',\r\n\]', ']')::jsonb
            || '{"Id": 3,"Value":"Гармонизация по классификатору ЦОД","Name":"HarmonizationCOD" }') val
          from core_reference
          where referenceid = 801
    )
    select jsonb_pretty(jsonb_agg(val) ) from sel)
where referenceid = 801;

INSERT INTO core_register (registerid, registername, registerdescription, allpri_table, object_table, quant_table, track_changes_column, storage_type, object_sequence, is_virtual, contains_quant_in_future, db_connection_name, track_changes_userid, track_changes_date, is_deleted, allpri_partitioning, main_register) VALUES (214, 'KO.CodDictionary', 'Справочник ЦОД', null, null, 'KO_COD_DICTIONARY', null, 4, 'REG_OBJECT_SEQ', 0, 0, null, null, null, 0, null, null)
on conflict do update set (registerid, registername, registerdescription, allpri_table, object_table, quant_table, track_changes_column, storage_type, object_sequence, is_virtual, contains_quant_in_future, db_connection_name, track_changes_userid, track_changes_date, is_deleted, allpri_partitioning, main_register) = (214, 'KO.CodDictionary', 'Справочник ЦОД', null, null, 'KO_COD_DICTIONARY', null, 4, 'REG_OBJECT_SEQ', 0, 0, null, null, null, 0, null, null);

INSERT INTO core_register_attribute (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) VALUES (21400100, 'Идентификатор', 214, 1, null, null, 'ID', null, null, 1, null, null, 'Id', 0, null, null, null, 0, null, null, 0)
ON CONFLICT DO UPDATE SET (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) = (21400100, 'Идентификатор', 214, 1, null, null, 'ID', null, null, 1, null, null, 'Id', 0, null, null, null, 0, null, null, 0);
INSERT INTO core_register_attribute (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) VALUES (21400200, 'Идентификатор задания ЦОД', 214, 1, null, null, 'ID_CODJOB', null, null, null, null, null, 'IdCodjob', 0, null, null, null, 0, null, null, 0)
ON CONFLICT DO UPDATE SET (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) = (21400200, 'Идентификатор задания ЦОД', 214, 1, null, null, 'ID_CODJOB', null, null, null, null, null, 'IdCodjob', 0, null, null, null, 0, null, null, 0);
INSERT INTO core_register_attribute (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) VALUES (21400300, 'Значение', 214, 4, null, null, 'VALUE', null, null, null, null, null, 'Value', 1, null, null, null, 0, null, null, 0)
ON CONFLICT DO UPDATE SET (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) = (21400300, 'Значение', 214, 4, null, null, 'VALUE', null, null, null, null, null, 'Value', 1, null, null, null, 0, null, null, 0);
INSERT INTO core_register_attribute (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) VALUES (21400400, 'Код', 214, 4, null, null, 'CODE', null, null, null, null, null, 'Code', 1, null, null, null, 0, null, null, 0)
ON CONFLICT DO UPDATE SET (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) = (21400400, 'Код', 214, 4, null, null, 'CODE', null, null, null, null, null, 'Code', 1, null, null, null, 0, null, null, 0);
INSERT INTO core_register_attribute (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) VALUES (21400500, ' Источник', 214, 4, null, null, 'SOURCE', null, null, null, null, null, 'Source', 1, null, null, null, 0, null, null, 0)
ON CONFLICT DO UPDATE SET (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) = (21400500, ' Источник', 214, 4, null, null, 'SOURCE', null, null, null, null, null, 'Source', 1, null, null, null, 0, null, null, 0);
INSERT INTO core_register_attribute (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) VALUES (21400600, 'ФИО эксперта', 214, 4, null, null, 'EXPERT', null, null, null, null, null, 'Expert', 1, null, null, null, 0, null, null, 0)
ON CONFLICT DO UPDATE SET (id, name, registerid, type, parentid, referenceid, value_field, code_field, value_template, primary_key, user_key, qscolumn, internal_name, is_nullable, description, layout, export_column_name, is_deleted, change_user_id, change_date, hidden) = (21400600, 'ФИО эксперта', 214, 4, null, null, 'EXPERT', null, null, null, null, null, 'Expert', 1, null, null, null, 0, null, null, 0);