//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by xsd, Version=4.8.3928.0.
//
namespace KadOzenka.Dal.YRLParser {
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    [System.Xml.Serialization.XmlRootAttribute("realty-feed", Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06", IsNullable=false)]
    public partial class realtyfeed {

        private string generationdateField;

        private realtyfeedOffer[] offerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("generation-date")]
        public string generationdate {
            get {
                return this.generationdateField;
            }
            set {
                this.generationdateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("offer")]
        public realtyfeedOffer[] offer {
            get {
                return this.offerField;
            }
            set {
                this.offerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOffer {

        private string newobjectidField;

        private string typeField;

        private string propertytypeField;

        private string categoryField;

        private string garagetypeField;

        private string lotnumberField;

        private string cadastralnumberField;

        private string urlField;

        private string creationdateField;

        private string vasField;

        private string villagenameField;

        private string yandexvillageidField;

        private string lastupdatedateField;

        private string payedadvField;

        private string manuallyaddedField;

        private string renovationField;

        private string descriptionField;

        private string roomsField;

        private string phoneField;

        private string floorField;

        private string floorstotalField;

        private string buildingnameField;

        private string buildingtypeField;

        private string buildingseriesField;

        private string builtyearField;

        private string ceilingheightField;

        private string rubbishchuteField;

        private string lottypeField;

        private string watersupplyField;

        private string seweragesupplyField;

        private string electricitysupplyField;

        private string gassupplyField;

        private string roomsofferedField;

        private string roomfurnitureField;

        private string bathroomunitField;

        private string televisionField;

        private string washingmachineField;

        private string refrigeratorField;

        private string internetField;

        private string rentpledgeField;

        private string taxationformField;

        private string dealstatusField;

        private string haggleField;

        private string mortgageField;

        private string prepaymentField;

        private string agentfeeField;

        private string notforagentsField;

        private string utilitiesincludedField;

        private string disableflatplanguessField;

        private string videopreviewField;

        private string qualityField;

        private string imageField;

        private string isimageorderchangeallowedField;

        private string apartmentsField;

        private string studioField;

        private string openplanField;

        private string roomstypeField;

        private string windowviewField;

        private string balconyField;

        private string airconditionerField;

        private string kitchenfurnitureField;

        private string dishwasherField;

        private string builtintechField;

        private string floorcoveringField;

        private string withchildrenField;

        private string withpetsField;

        private string yandexbuildingidField;

        private string yandexhouseidField;

        private string buildingsectionField;

        private string guardedbuildingField;

        private string pmgField;

        private string accesscontrolsystemField;

        private string liftField;

        private string heatingsupplyField;

        private string toiletField;

        private string showerField;

        private string poolField;

        private string billiardField;

        private string saunaField;

        private string parkingField;

        private string parkingplacesField;

        private string parkingplacepriceField;

        private string parkingguestField;

        private string parkingguestplacesField;

        private string alarmField;

        private string flatalarmField;

        private string securityField;

        private string iseliteField;

        private string automaticgatesField;

        private string cctvField;

        private string firealarmField;

        private string inspectionpitField;

        private string cellarField;

        private string carwashField;

        private string autorepairField;

        private string newparkingField;

        private string ownershiptypeField;

        private string garagenameField;

        private string parkingtypeField;

        private string[] commercialtypeField;

        private string[] commercialbuildingtypeField;

        private string[] purposeField;

        private string[] purposewarehouseField;

        private string cleaningincludedField;

        private string electricityincludedField;

        private string entrancetypeField;

        private string phonelinesField;

        private string addingphoneonrequestField;

        private string selfselectiontelecomField;

        private string ventilationField;

        private string electriccapacityField;

        private string windowtypeField;

        private string officeclassField;

        private string twentyfoursevenField;

        private string eatingfacilitiesField;

        private string resposniblestorageField;

        private string palletpriceField;

        private string freightelevatorField;

        private string truckentranceField;

        private string rampField;

        private string railwayField;

        private string officewarehouseField;

        private string openareaField;

        private string servicethreeplField;

        private string temperatirecommentField;

        private realtyfeedOfferLocation locationField;

        private realtyfeedOfferSalesagent salesagentField;

        private realtyfeedOfferPrice priceField;

        private realtyfeedOfferArea areaField;

        private realtyfeedOfferRoomspace[] roomspaceField;

        private realtyfeedOfferKitchenspace kitchenspaceField;

        private realtyfeedOfferLivingspace livingspaceField;

        private realtyfeedOfferLotarea lotareaField;

        private string internalidField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("newobject-id")]
        public string newobjectid {
            get {
                return this.newobjectidField;
            }
            set {
                this.newobjectidField = value;
            }
        }

        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("property-type")]
        public string propertytype {
            get {
                return this.propertytypeField;
            }
            set {
                this.propertytypeField = value;
            }
        }

        /// <remarks/>
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("garage-type")]
        public string garagetype {
            get {
                return this.garagetypeField;
            }
            set {
                this.garagetypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lot-number")]
        public string lotnumber {
            get {
                return this.lotnumberField;
            }
            set {
                this.lotnumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cadastral-number")]
        public string cadastralnumber {
            get {
                return this.cadastralnumberField;
            }
            set {
                this.cadastralnumberField = value;
            }
        }

        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("creation-date")]
        public string creationdate {
            get {
                return this.creationdateField;
            }
            set {
                this.creationdateField = value;
            }
        }

        /// <remarks/>
        public string vas {
            get {
                return this.vasField;
            }
            set {
                this.vasField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("village-name")]
        public string villagename {
            get {
                return this.villagenameField;
            }
            set {
                this.villagenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("yandex-village-id")]
        public string yandexvillageid {
            get {
                return this.yandexvillageidField;
            }
            set {
                this.yandexvillageidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("last-update-date")]
        public string lastupdatedate {
            get {
                return this.lastupdatedateField;
            }
            set {
                this.lastupdatedateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("payed-adv")]
        public string payedadv {
            get {
                return this.payedadvField;
            }
            set {
                this.payedadvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("manually-added")]
        public string manuallyadded {
            get {
                return this.manuallyaddedField;
            }
            set {
                this.manuallyaddedField = value;
            }
        }

        /// <remarks/>
        public string renovation {
            get {
                return this.renovationField;
            }
            set {
                this.renovationField = value;
            }
        }

        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string rooms {
            get {
                return this.roomsField;
            }
            set {
                this.roomsField = value;
            }
        }

        /// <remarks/>
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        public string floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("floors-total")]
        public string floorstotal {
            get {
                return this.floorstotalField;
            }
            set {
                this.floorstotalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("building-name")]
        public string buildingname {
            get {
                return this.buildingnameField;
            }
            set {
                this.buildingnameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("building-type")]
        public string buildingtype {
            get {
                return this.buildingtypeField;
            }
            set {
                this.buildingtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("building-series")]
        public string buildingseries {
            get {
                return this.buildingseriesField;
            }
            set {
                this.buildingseriesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("built-year")]
        public string builtyear {
            get {
                return this.builtyearField;
            }
            set {
                this.builtyearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ceiling-height")]
        public string ceilingheight {
            get {
                return this.ceilingheightField;
            }
            set {
                this.ceilingheightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rubbish-chute")]
        public string rubbishchute {
            get {
                return this.rubbishchuteField;
            }
            set {
                this.rubbishchuteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lot-type")]
        public string lottype {
            get {
                return this.lottypeField;
            }
            set {
                this.lottypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("water-supply")]
        public string watersupply {
            get {
                return this.watersupplyField;
            }
            set {
                this.watersupplyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sewerage-supply")]
        public string seweragesupply {
            get {
                return this.seweragesupplyField;
            }
            set {
                this.seweragesupplyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("electricity-supply")]
        public string electricitysupply {
            get {
                return this.electricitysupplyField;
            }
            set {
                this.electricitysupplyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gas-supply")]
        public string gassupply {
            get {
                return this.gassupplyField;
            }
            set {
                this.gassupplyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rooms-offered")]
        public string roomsoffered {
            get {
                return this.roomsofferedField;
            }
            set {
                this.roomsofferedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("room-furniture")]
        public string roomfurniture {
            get {
                return this.roomfurnitureField;
            }
            set {
                this.roomfurnitureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bathroom-unit")]
        public string bathroomunit {
            get {
                return this.bathroomunitField;
            }
            set {
                this.bathroomunitField = value;
            }
        }

        /// <remarks/>
        public string television {
            get {
                return this.televisionField;
            }
            set {
                this.televisionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("washing-machine")]
        public string washingmachine {
            get {
                return this.washingmachineField;
            }
            set {
                this.washingmachineField = value;
            }
        }

        /// <remarks/>
        public string refrigerator {
            get {
                return this.refrigeratorField;
            }
            set {
                this.refrigeratorField = value;
            }
        }

        /// <remarks/>
        public string internet {
            get {
                return this.internetField;
            }
            set {
                this.internetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rent-pledge")]
        public string rentpledge {
            get {
                return this.rentpledgeField;
            }
            set {
                this.rentpledgeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("taxation-form")]
        public string taxationform {
            get {
                return this.taxationformField;
            }
            set {
                this.taxationformField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("deal-status")]
        public string dealstatus {
            get {
                return this.dealstatusField;
            }
            set {
                this.dealstatusField = value;
            }
        }

        /// <remarks/>
        public string haggle {
            get {
                return this.haggleField;
            }
            set {
                this.haggleField = value;
            }
        }

        /// <remarks/>
        public string mortgage {
            get {
                return this.mortgageField;
            }
            set {
                this.mortgageField = value;
            }
        }

        /// <remarks/>
        public string prepayment {
            get {
                return this.prepaymentField;
            }
            set {
                this.prepaymentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("agent-fee")]
        public string agentfee {
            get {
                return this.agentfeeField;
            }
            set {
                this.agentfeeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("not-for-agents")]
        public string notforagents {
            get {
                return this.notforagentsField;
            }
            set {
                this.notforagentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("utilities-included")]
        public string utilitiesincluded {
            get {
                return this.utilitiesincludedField;
            }
            set {
                this.utilitiesincludedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("disable-flat-plan-guess")]
        public string disableflatplanguess {
            get {
                return this.disableflatplanguessField;
            }
            set {
                this.disableflatplanguessField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("video-preview")]
        public string videopreview {
            get {
                return this.videopreviewField;
            }
            set {
                this.videopreviewField = value;
            }
        }

        /// <remarks/>
        public string quality {
            get {
                return this.qualityField;
            }
            set {
                this.qualityField = value;
            }
        }

        /// <remarks/>
        public string image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("is-image-order-change-allowed")]
        public string isimageorderchangeallowed {
            get {
                return this.isimageorderchangeallowedField;
            }
            set {
                this.isimageorderchangeallowedField = value;
            }
        }

        /// <remarks/>
        public string apartments {
            get {
                return this.apartmentsField;
            }
            set {
                this.apartmentsField = value;
            }
        }

        /// <remarks/>
        public string studio {
            get {
                return this.studioField;
            }
            set {
                this.studioField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("open-plan")]
        public string openplan {
            get {
                return this.openplanField;
            }
            set {
                this.openplanField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("rooms-type")]
        public string roomstype {
            get {
                return this.roomstypeField;
            }
            set {
                this.roomstypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("window-view")]
        public string windowview {
            get {
                return this.windowviewField;
            }
            set {
                this.windowviewField = value;
            }
        }

        /// <remarks/>
        public string balcony {
            get {
                return this.balconyField;
            }
            set {
                this.balconyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("air-conditioner")]
        public string airconditioner {
            get {
                return this.airconditionerField;
            }
            set {
                this.airconditionerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("kitchen-furniture")]
        public string kitchenfurniture {
            get {
                return this.kitchenfurnitureField;
            }
            set {
                this.kitchenfurnitureField = value;
            }
        }

        /// <remarks/>
        public string dishwasher {
            get {
                return this.dishwasherField;
            }
            set {
                this.dishwasherField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("built-in-tech")]
        public string builtintech {
            get {
                return this.builtintechField;
            }
            set {
                this.builtintechField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("floor-covering")]
        public string floorcovering {
            get {
                return this.floorcoveringField;
            }
            set {
                this.floorcoveringField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("with-children")]
        public string withchildren {
            get {
                return this.withchildrenField;
            }
            set {
                this.withchildrenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("with-pets")]
        public string withpets {
            get {
                return this.withpetsField;
            }
            set {
                this.withpetsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("yandex-building-id")]
        public string yandexbuildingid {
            get {
                return this.yandexbuildingidField;
            }
            set {
                this.yandexbuildingidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("yandex-house-id")]
        public string yandexhouseid {
            get {
                return this.yandexhouseidField;
            }
            set {
                this.yandexhouseidField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("building-section")]
        public string buildingsection {
            get {
                return this.buildingsectionField;
            }
            set {
                this.buildingsectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("guarded-building")]
        public string guardedbuilding {
            get {
                return this.guardedbuildingField;
            }
            set {
                this.guardedbuildingField = value;
            }
        }

        /// <remarks/>
        public string pmg {
            get {
                return this.pmgField;
            }
            set {
                this.pmgField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("access-control-system")]
        public string accesscontrolsystem {
            get {
                return this.accesscontrolsystemField;
            }
            set {
                this.accesscontrolsystemField = value;
            }
        }

        /// <remarks/>
        public string lift {
            get {
                return this.liftField;
            }
            set {
                this.liftField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("heating-supply")]
        public string heatingsupply {
            get {
                return this.heatingsupplyField;
            }
            set {
                this.heatingsupplyField = value;
            }
        }

        /// <remarks/>
        public string toilet {
            get {
                return this.toiletField;
            }
            set {
                this.toiletField = value;
            }
        }

        /// <remarks/>
        public string shower {
            get {
                return this.showerField;
            }
            set {
                this.showerField = value;
            }
        }

        /// <remarks/>
        public string pool {
            get {
                return this.poolField;
            }
            set {
                this.poolField = value;
            }
        }

        /// <remarks/>
        public string billiard {
            get {
                return this.billiardField;
            }
            set {
                this.billiardField = value;
            }
        }

        /// <remarks/>
        public string sauna {
            get {
                return this.saunaField;
            }
            set {
                this.saunaField = value;
            }
        }

        /// <remarks/>
        public string parking {
            get {
                return this.parkingField;
            }
            set {
                this.parkingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parking-places")]
        public string parkingplaces {
            get {
                return this.parkingplacesField;
            }
            set {
                this.parkingplacesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parking-placeprice")]
        public string parkingplaceprice {
            get {
                return this.parkingplacepriceField;
            }
            set {
                this.parkingplacepriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parking-guest")]
        public string parkingguest {
            get {
                return this.parkingguestField;
            }
            set {
                this.parkingguestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parking-guest-places")]
        public string parkingguestplaces {
            get {
                return this.parkingguestplacesField;
            }
            set {
                this.parkingguestplacesField = value;
            }
        }

        /// <remarks/>
        public string alarm {
            get {
                return this.alarmField;
            }
            set {
                this.alarmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("flat-alarm")]
        public string flatalarm {
            get {
                return this.flatalarmField;
            }
            set {
                this.flatalarmField = value;
            }
        }

        /// <remarks/>
        public string security {
            get {
                return this.securityField;
            }
            set {
                this.securityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("is-elite")]
        public string iselite {
            get {
                return this.iseliteField;
            }
            set {
                this.iseliteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("automatic-gates")]
        public string automaticgates {
            get {
                return this.automaticgatesField;
            }
            set {
                this.automaticgatesField = value;
            }
        }

        /// <remarks/>
        public string cctv {
            get {
                return this.cctvField;
            }
            set {
                this.cctvField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fire-alarm")]
        public string firealarm {
            get {
                return this.firealarmField;
            }
            set {
                this.firealarmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inspection-pit")]
        public string inspectionpit {
            get {
                return this.inspectionpitField;
            }
            set {
                this.inspectionpitField = value;
            }
        }

        /// <remarks/>
        public string cellar {
            get {
                return this.cellarField;
            }
            set {
                this.cellarField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("car-wash")]
        public string carwash {
            get {
                return this.carwashField;
            }
            set {
                this.carwashField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("auto-repair")]
        public string autorepair {
            get {
                return this.autorepairField;
            }
            set {
                this.autorepairField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("new-parking")]
        public string newparking {
            get {
                return this.newparkingField;
            }
            set {
                this.newparkingField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ownership-type")]
        public string ownershiptype {
            get {
                return this.ownershiptypeField;
            }
            set {
                this.ownershiptypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("garage-name")]
        public string garagename {
            get {
                return this.garagenameField;
            }
            set {
                this.garagenameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parking-type")]
        public string parkingtype {
            get {
                return this.parkingtypeField;
            }
            set {
                this.parkingtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("commercial-type")]
        public string[] commercialtype {
            get {
                return this.commercialtypeField;
            }
            set {
                this.commercialtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("commercial-building-type")]
        public string[] commercialbuildingtype {
            get {
                return this.commercialbuildingtypeField;
            }
            set {
                this.commercialbuildingtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("purpose")]
        public string[] purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("purpose-warehouse")]
        public string[] purposewarehouse {
            get {
                return this.purposewarehouseField;
            }
            set {
                this.purposewarehouseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cleaning-included")]
        public string cleaningincluded {
            get {
                return this.cleaningincludedField;
            }
            set {
                this.cleaningincludedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("electricity-included")]
        public string electricityincluded {
            get {
                return this.electricityincludedField;
            }
            set {
                this.electricityincludedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("entrance-type")]
        public string entrancetype {
            get {
                return this.entrancetypeField;
            }
            set {
                this.entrancetypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone-lines")]
        public string phonelines {
            get {
                return this.phonelinesField;
            }
            set {
                this.phonelinesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("adding-phone-on-request")]
        public string addingphoneonrequest {
            get {
                return this.addingphoneonrequestField;
            }
            set {
                this.addingphoneonrequestField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("self-selection-telecom")]
        public string selfselectiontelecom {
            get {
                return this.selfselectiontelecomField;
            }
            set {
                this.selfselectiontelecomField = value;
            }
        }

        /// <remarks/>
        public string ventilation {
            get {
                return this.ventilationField;
            }
            set {
                this.ventilationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("electric-capacity")]
        public string electriccapacity {
            get {
                return this.electriccapacityField;
            }
            set {
                this.electriccapacityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("window-type")]
        public string windowtype {
            get {
                return this.windowtypeField;
            }
            set {
                this.windowtypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("office-class")]
        public string officeclass {
            get {
                return this.officeclassField;
            }
            set {
                this.officeclassField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("twenty-four-seven")]
        public string twentyfourseven {
            get {
                return this.twentyfoursevenField;
            }
            set {
                this.twentyfoursevenField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("eating-facilities")]
        public string eatingfacilities {
            get {
                return this.eatingfacilitiesField;
            }
            set {
                this.eatingfacilitiesField = value;
            }
        }

        /// <remarks/>
        public string resposniblestorage {
            get {
                return this.resposniblestorageField;
            }
            set {
                this.resposniblestorageField = value;
            }
        }

        /// <remarks/>
        public string palletprice {
            get {
                return this.palletpriceField;
            }
            set {
                this.palletpriceField = value;
            }
        }

        /// <remarks/>
        public string freightelevator {
            get {
                return this.freightelevatorField;
            }
            set {
                this.freightelevatorField = value;
            }
        }

        /// <remarks/>
        public string truckentrance {
            get {
                return this.truckentranceField;
            }
            set {
                this.truckentranceField = value;
            }
        }

        /// <remarks/>
        public string ramp {
            get {
                return this.rampField;
            }
            set {
                this.rampField = value;
            }
        }

        /// <remarks/>
        public string railway {
            get {
                return this.railwayField;
            }
            set {
                this.railwayField = value;
            }
        }

        /// <remarks/>
        public string officewarehouse {
            get {
                return this.officewarehouseField;
            }
            set {
                this.officewarehouseField = value;
            }
        }

        /// <remarks/>
        public string openarea {
            get {
                return this.openareaField;
            }
            set {
                this.openareaField = value;
            }
        }

        /// <remarks/>
        public string servicethreepl {
            get {
                return this.servicethreeplField;
            }
            set {
                this.servicethreeplField = value;
            }
        }

        /// <remarks/>
        public string temperatirecomment {
            get {
                return this.temperatirecommentField;
            }
            set {
                this.temperatirecommentField = value;
            }
        }

        /// <remarks/>
        public realtyfeedOfferLocation location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sales-agent")]
        public realtyfeedOfferSalesagent salesagent {
            get {
                return this.salesagentField;
            }
            set {
                this.salesagentField = value;
            }
        }

        /// <remarks/>
        public realtyfeedOfferPrice price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }

        /// <remarks/>
        public realtyfeedOfferArea area {
            get {
                return this.areaField;
            }
            set {
                this.areaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("room-space")]
        public realtyfeedOfferRoomspace[] roomspace {
            get {
                return this.roomspaceField;
            }
            set {
                this.roomspaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("kitchen-space")]
        public realtyfeedOfferKitchenspace kitchenspace {
            get {
                return this.kitchenspaceField;
            }
            set {
                this.kitchenspaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("living-space")]
        public realtyfeedOfferLivingspace livingspace {
            get {
                return this.livingspaceField;
            }
            set {
                this.livingspaceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lot-area")]
        public realtyfeedOfferLotarea lotarea {
            get {
                return this.lotareaField;
            }
            set {
                this.lotareaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("internal-id")]
        public string internalid {
            get {
                return this.internalidField;
            }
            set {
                this.internalidField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOfferLocation {

        private string countryField;

        private string regionField;

        private string districtField;

        private string localitynameField;

        private string sublocalitynameField;

        private string addressField;

        private string apartmentField;

        private string directionField;

        private string distanceField;

        private string latitudeField;

        private string longitudeField;

        private string railwaystationField;

        private realtyfeedOfferLocationMetro[] metroField;

        /// <remarks/>
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string region {
            get {
                return this.regionField;
            }
            set {
                this.regionField = value;
            }
        }

        /// <remarks/>
        public string district {
            get {
                return this.districtField;
            }
            set {
                this.districtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locality-name")]
        public string localityname {
            get {
                return this.localitynameField;
            }
            set {
                this.localitynameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sub-locality-name")]
        public string sublocalityname {
            get {
                return this.sublocalitynameField;
            }
            set {
                this.sublocalitynameField = value;
            }
        }

        /// <remarks/>
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }

        /// <remarks/>
        public string apartment {
            get {
                return this.apartmentField;
            }
            set {
                this.apartmentField = value;
            }
        }

        /// <remarks/>
        public string direction {
            get {
                return this.directionField;
            }
            set {
                this.directionField = value;
            }
        }

        /// <remarks/>
        public string distance {
            get {
                return this.distanceField;
            }
            set {
                this.distanceField = value;
            }
        }

        /// <remarks/>
        public string latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }

        /// <remarks/>
        public string longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("railway-station")]
        public string railwaystation {
            get {
                return this.railwaystationField;
            }
            set {
                this.railwaystationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("metro")]
        public realtyfeedOfferLocationMetro[] metro {
            get {
                return this.metroField;
            }
            set {
                this.metroField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOfferLocationMetro {

        private string nameField;

        private string timeonfootField;

        private string timeontransportField;

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("time-on-foot")]
        public string timeonfoot {
            get {
                return this.timeonfootField;
            }
            set {
                this.timeonfootField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("time-on-transport")]
        public string timeontransport {
            get {
                return this.timeontransportField;
            }
            set {
                this.timeontransportField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOfferSalesagent {

        private string nameField;

        private string categoryField;

        private string organizationField;

        private string agencyidField;

        private string urlField;

        private string emailField;

        private string photoField;

        private string partnerField;

        private realtyfeedOfferSalesagentPhone[] phoneField;

        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string category {
            get {
                return this.categoryField;
            }
            set {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        public string organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("agency-id")]
        public string agencyid {
            get {
                return this.agencyidField;
            }
            set {
                this.agencyidField = value;
            }
        }

        /// <remarks/>
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }

        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }

        /// <remarks/>
        public string photo {
            get {
                return this.photoField;
            }
            set {
                this.photoField = value;
            }
        }

        /// <remarks/>
        public string partner {
            get {
                return this.partnerField;
            }
            set {
                this.partnerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("phone", IsNullable=true)]
        public realtyfeedOfferSalesagentPhone[] phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOfferSalesagentPhone {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOfferPrice {

        private string valueField;

        private string currencyField;

        private string periodField;

        private string unitField;

        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }

        /// <remarks/>
        public string period {
            get {
                return this.periodField;
            }
            set {
                this.periodField = value;
            }
        }

        /// <remarks/>
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOfferArea {

        private string valueField;

        private string unitField;

        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOfferRoomspace {

        private string valueField;

        private string unitField;

        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOfferKitchenspace {

        private string valueField;

        private string unitField;

        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOfferLivingspace {

        private string valueField;

        private string unitField;

        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    public partial class realtyfeedOfferLotarea {

        private string valueField;

        private string unitField;

        /// <remarks/>
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://webmaster.yandex.ru/schemas/feed/realty/2010-06", IsNullable=false)]
    public partial class NewDataSet {

        private realtyfeed[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("realty-feed")]
        public realtyfeed[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}
