//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KadOzenka.Dal.CodDictionary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CodMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KadOzenka.Dal.CodDictionary.Resources.CodMessages", typeof(CodMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дожно быть заполнено хотя бы одно значение.
        /// </summary>
        public static string AtLeastOneDictionaryValueNeeded {
            get {
                return ResourceManager.GetString("AtLeastOneDictionaryValueNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указано Имя справочника.
        /// </summary>
        public static string EmptyDictionaryName {
            get {
                return ResourceManager.GetString("EmptyDictionaryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение {0} не может быть пустым.
        /// </summary>
        public static string EmptyValueName {
            get {
                return ResourceManager.GetString("EmptyValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нельзя создать значение с зарезервированным именем.
        /// </summary>
        public static string ForbiddenValueName {
            get {
                return ResourceManager.GetString("ForbiddenValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Максимальное количество значений -.
        /// </summary>
        public static string MaxValuesCountExceed {
            get {
                return ResourceManager.GetString("MaxValuesCountExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Минимальное количество значений -.
        /// </summary>
        public static string MinValuesCountExceed {
            get {
                return ResourceManager.GetString("MinValuesCountExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указаны Значения.
        /// </summary>
        public static string NoDictionaryValues {
            get {
                return ResourceManager.GetString("NoDictionaryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не указан Код.
        /// </summary>
        public static string NoValueCode {
            get {
                return ResourceManager.GetString("NoValueCode", resourceCulture);
            }
        }
    }
}
