/* 
 * CadAppraisalDataApi
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using CadAppraisalDataApi.Models;
using CommonSdks.ConfigurationManagers.WebClients;
using RestSharp;
using IO.Swagger.Client;
using IO.Swagger.Model;
using Serilog;
using Serilog.Context;

namespace KadOzenka.WebClients.ReonClient.Api
{
    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IRosreestrDataApi : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Возвращает документ из папки для загрузок кадастровой оценки
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="loadId">Идентификатор загрузки</param>
        /// <param name="fname">Название файла</param>
        /// <returns>Object</returns>
        string RosreestrDataGetFileByIdCA(long? loadId, string fname);

        /// <summary>
        /// Возвращает документ из папки для загрузок кадастровой оценки
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="loadId">Идентификатор загрузки</param>
        /// <param name="fname">Название файла</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<string> RosreestrDataGetFileByIdCAWithHttpInfo(long? loadId, string fname);
        /// <summary>
        /// Возвращает документ из файлового хранилища по id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="fname"></param>
        /// <returns>Object</returns>
        object RosreestrDataGetFileByIdZD(long? id, string fname);

        /// <summary>
        /// Возвращает документ из файлового хранилища по id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="fname"></param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<object> RosreestrDataGetFileByIdZDWithHttpInfo(long? id, string fname);
        /// <summary>
        /// Возвращает графические факторы по кадастровому номеру
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="cadNum">Кадастровый номер</param>
        /// <param name="dateAppraisal">Дата оценки</param>
        /// <returns>Object</returns>
        GraphFactorsData RosreestrDataGetGraphFactorsByCadNum(string cadNum, DateTime? dateAppraisal);

        /// <summary>
        /// Возвращает графические факторы по кадастровому номеру
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="cadNum">Кадастровый номер</param>
        /// <param name="dateAppraisal">Дата оценки</param>
        /// <returns>ApiResponse of Object</returns>
        ApiResponse<GraphFactorsData> RosreestrDataGetGraphFactorsByCadNumWithHttpInfo(string cadNum, DateTime? dateAppraisal);
        /// <summary>
        /// Возвращает данные Росреестра по диапазону дат включительно
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dateFrom">Дата с</param>
        /// <param name="dateTo">Дата по</param>
        /// <returns>List&lt;RRDataLoadModel&gt;</returns>
        List<RRDataLoadModel> RosreestrDataGetRRData(DateTime? dateFrom, DateTime? dateTo);

        /// <summary>
        /// Возвращает данные Росреестра по диапазону дат включительно
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dateFrom">Дата с</param>
        /// <param name="dateTo">Дата по</param>
        /// <returns>ApiResponse of List&lt;RRDataLoadModel&gt;</returns>
        ApiResponse<List<RRDataLoadModel>> RosreestrDataGetRRDataWithHttpInfo(DateTime? dateFrom, DateTime? dateTo);
        #endregion Synchronous Operations
        #region Asynchronous Operations
        /// <summary>
        /// Возвращает документ из папки для загрузок кадастровой оценки
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="loadId">Идентификатор загрузки</param>
        /// <param name="fname">Название файла</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<object> RosreestrDataGetFileByIdCAAsync(long? loadId, string fname);

        /// <summary>
        /// Возвращает документ из папки для загрузок кадастровой оценки
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="loadId">Идентификатор загрузки</param>
        /// <param name="fname">Название файла</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<object>> RosreestrDataGetFileByIdCAAsyncWithHttpInfo(long? loadId, string fname);
        /// <summary>
        /// Возвращает документ из файлового хранилища по id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="fname"></param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<object> RosreestrDataGetFileByIdZDAsync(long? id, string fname);

        /// <summary>
        /// Возвращает документ из файлового хранилища по id
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="fname"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<object>> RosreestrDataGetFileByIdZDAsyncWithHttpInfo(long? id, string fname);
        /// <summary>
        /// Возвращает графические факторы по кадастровому номеру
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="cadNum">Кадастровый номер</param>
        /// <param name="dateAppraisal">Дата оценки</param>
        /// <returns>Task of Object</returns>
        System.Threading.Tasks.Task<object> RosreestrDataGetGraphFactorsByCadNumAsync(string cadNum, DateTime? dateAppraisal);

        /// <summary>
        /// Возвращает графические факторы по кадастровому номеру
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="cadNum">Кадастровый номер</param>
        /// <param name="dateAppraisal">Дата оценки</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        System.Threading.Tasks.Task<ApiResponse<object>> RosreestrDataGetGraphFactorsByCadNumAsyncWithHttpInfo(string cadNum, DateTime? dateAppraisal);
        /// <summary>
        /// Возвращает данные Росреестра по диапазону дат включительно
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dateFrom">Дата с</param>
        /// <param name="dateTo">Дата по</param>
        /// <returns>Task of List&lt;RRDataLoadModel&gt;</returns>
        System.Threading.Tasks.Task<List<RRDataLoadModel>> RosreestrDataGetRRDataAsync(DateTime? dateFrom, DateTime? dateTo);

        /// <summary>
        /// Возвращает данные Росреестра по диапазону дат включительно
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dateFrom">Дата с</param>
        /// <param name="dateTo">Дата по</param>
        /// <returns>Task of ApiResponse (List&lt;RRDataLoadModel&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<RRDataLoadModel>>> RosreestrDataGetRRDataAsyncWithHttpInfo(DateTime? dateFrom, DateTime? dateTo);
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class RosreestrDataApi : IRosreestrDataApi
    {
        private ExceptionFactory _exceptionFactory = (name, response) => null;
        private readonly ILogger _log = Log.ForContext<RosreestrDataApi>();

        /// <summary>
        /// Initializes a new instance of the <see cref="RosreestrDataApi"/> class.
        /// </summary>
        /// <returns></returns>
        public RosreestrDataApi()
        {
            Configuration = new Configuration { BasePath = WebClientsConfig.Current.BaseUrl };

            ExceptionFactory = Configuration.DefaultExceptionFactory;
        }
        
        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return Configuration.ApiClient.RestClient.BaseUrl.ToString();
        }

        /// <summary>
        /// Sets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        [Obsolete("SetBasePath is deprecated, please do 'Configuration.ApiClient = new ApiClient(\"http://new-path\")' instead.")]
        public void SetBasePath(string basePath)
        {
            // do nothing
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Configuration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the default header.
        /// </summary>
        /// <returns>Dictionary of HTTP header</returns>
        [Obsolete("DefaultHeader is deprecated, please use Configuration.DefaultHeader instead.")]
        public IDictionary<string, string> DefaultHeader()
        {
            return new ReadOnlyDictionary<string, string>(Configuration.DefaultHeader);
        }

        /// <summary>
        /// Add default header.
        /// </summary>
        /// <param name="key">Header field name.</param>
        /// <param name="value">Header field value.</param>
        /// <returns></returns>
        [Obsolete("AddDefaultHeader is deprecated, please use Configuration.AddDefaultHeader instead.")]
        public void AddDefaultHeader(string key, string value)
        {
            Configuration.AddDefaultHeader(key, value);
        }

        /// <summary>
        /// Возвращает документ из папки для загрузок кадастровой оценки 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="loadId">Идентификатор загрузки</param>
        /// <param name="fname">Название файла</param>
        /// <returns>Object</returns>
        public string RosreestrDataGetFileByIdCA(long? loadId, string fname)
        {
            ApiResponse<string> localVarResponse = RosreestrDataGetFileByIdCAWithHttpInfo(loadId, fname);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Возвращает документ из папки для загрузок кадастровой оценки 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="loadId">Идентификатор загрузки</param>
        /// <param name="fname">Название файла</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse<string> RosreestrDataGetFileByIdCAWithHttpInfo(long? loadId, string fname)
        {
            // verify the required parameter 'loadId' is set
            if (loadId == null)
                throw new ApiException(400, "Missing required parameter 'loadId' when calling RosreestrDataApi->RosreestrDataGetFileByIdCA");
            // verify the required parameter 'fname' is set
            if (fname == null)
                throw new ApiException(400, "Missing required parameter 'fname' when calling RosreestrDataApi->RosreestrDataGetFileByIdCA");

            var localVarPath = "/RosreestrData/file_ca_by_id/{load_id}/{fname}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loadId != null) localVarPathParams.Add("load_id", Configuration.ApiClient.ParameterToString(loadId)); // path parameter
            if (fname != null) localVarPathParams.Add("fname", Configuration.ApiClient.ParameterToString(fname)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RosreestrDataGetFileByIdCA", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<string>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (string)Configuration.ApiClient.Deserialize(localVarResponse, typeof(string)));
        }

        /// <summary>
        /// Возвращает документ из папки для загрузок кадастровой оценки 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="loadId">Идентификатор загрузки</param>
        /// <param name="fname">Название файла</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<object> RosreestrDataGetFileByIdCAAsync(long? loadId, string fname)
        {
            ApiResponse<object> localVarResponse = await RosreestrDataGetFileByIdCAAsyncWithHttpInfo(loadId, fname);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Возвращает документ из папки для загрузок кадастровой оценки 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="loadId">Идентификатор загрузки</param>
        /// <param name="fname">Название файла</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<object>> RosreestrDataGetFileByIdCAAsyncWithHttpInfo(long? loadId, string fname)
        {
            // verify the required parameter 'loadId' is set
            if (loadId == null)
                throw new ApiException(400, "Missing required parameter 'loadId' when calling RosreestrDataApi->RosreestrDataGetFileByIdCA");
            // verify the required parameter 'fname' is set
            if (fname == null)
                throw new ApiException(400, "Missing required parameter 'fname' when calling RosreestrDataApi->RosreestrDataGetFileByIdCA");

            var localVarPath = "/RosreestrData/file_ca_by_id/{load_id}/{fname}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (loadId != null) localVarPathParams.Add("load_id", Configuration.ApiClient.ParameterToString(loadId)); // path parameter
            if (fname != null) localVarPathParams.Add("fname", Configuration.ApiClient.ParameterToString(fname)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RosreestrDataGetFileByIdCA", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                Configuration.ApiClient.Deserialize(localVarResponse, typeof(object)));
        }

        /// <summary>
        /// Возвращает документ из файлового хранилища по id 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="fname"></param>
        /// <returns>Object</returns>
        public object RosreestrDataGetFileByIdZD(long? id, string fname)
        {
            ApiResponse<object> localVarResponse = RosreestrDataGetFileByIdZDWithHttpInfo(id, fname);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Возвращает документ из файлового хранилища по id 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="fname"></param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse<object> RosreestrDataGetFileByIdZDWithHttpInfo(long? id, string fname)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling RosreestrDataApi->RosreestrDataGetFileByIdZD");
            // verify the required parameter 'fname' is set
            if (fname == null)
                throw new ApiException(400, "Missing required parameter 'fname' when calling RosreestrDataApi->RosreestrDataGetFileByIdZD");

            var localVarPath = "/RosreestrData/file_zd_by_id/{id}/{fname}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (fname != null) localVarPathParams.Add("fname", Configuration.ApiClient.ParameterToString(fname)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            LogContext.PushProperty("AbsoluteUri", localVarResponse.ResponseUri.AbsoluteUri);
            LogContext.PushProperty("Code", localVarStatusCode);
            LogContext.PushProperty("DocId", id);
            LogContext.PushProperty("Fname", fname);
            _log.Verbose("Запрос документа из файлового хранилища");

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RosreestrDataGetFileByIdZD", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                Configuration.ApiClient.Deserialize(localVarResponse, typeof(object)));
        }

        /// <summary>
        /// Возвращает документ из файлового хранилища по id 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="fname"></param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<object> RosreestrDataGetFileByIdZDAsync(long? id, string fname)
        {
            ApiResponse<object> localVarResponse = await RosreestrDataGetFileByIdZDAsyncWithHttpInfo(id, fname);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Возвращает документ из файлового хранилища по id 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="id"></param>
        /// <param name="fname"></param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<object>> RosreestrDataGetFileByIdZDAsyncWithHttpInfo(long? id, string fname)
        {
            // verify the required parameter 'id' is set
            if (id == null)
                throw new ApiException(400, "Missing required parameter 'id' when calling RosreestrDataApi->RosreestrDataGetFileByIdZD");
            // verify the required parameter 'fname' is set
            if (fname == null)
                throw new ApiException(400, "Missing required parameter 'fname' when calling RosreestrDataApi->RosreestrDataGetFileByIdZD");

            var localVarPath = "/RosreestrData/file_zd_by_id/{id}/{fname}";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (id != null) localVarPathParams.Add("id", Configuration.ApiClient.ParameterToString(id)); // path parameter
            if (fname != null) localVarPathParams.Add("fname", Configuration.ApiClient.ParameterToString(fname)); // path parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            _log.ForContext("AbsoluteUri", localVarResponse.ResponseUri.AbsoluteUri)
               .ForContext("Code", localVarStatusCode)
               .ForContext("DocId", id)
               .ForContext("Fname", fname)
               .Information("Запрос документа из файлового хранилища");

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RosreestrDataGetFileByIdZD", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                Configuration.ApiClient.Deserialize(localVarResponse, typeof(object)));
        }

        /// <summary>
        /// Возвращает графические факторы по кадастровому номеру 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="cadNum">Кадастровый номер</param>
        /// <param name="dateAppraisal">Дата оценки</param>
        /// <returns>Object</returns>
        public GraphFactorsData RosreestrDataGetGraphFactorsByCadNum(string cadNum, DateTime? dateAppraisal)
        {
            ApiResponse<GraphFactorsData> localVarResponse = RosreestrDataGetGraphFactorsByCadNumWithHttpInfo(cadNum, dateAppraisal);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Возвращает графические факторы по кадастровому номеру 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="cadNum">Кадастровый номер</param>
        /// <param name="dateAppraisal">Дата оценки</param>
        /// <returns>ApiResponse of Object</returns>
        public ApiResponse<GraphFactorsData> RosreestrDataGetGraphFactorsByCadNumWithHttpInfo(string cadNum, DateTime? dateAppraisal)
        {
            // verify the required parameter 'cadNum' is set
            if (cadNum == null)
                throw new ApiException(400, "Missing required parameter 'cadNum' when calling RosreestrDataApi->RosreestrDataGetGraphFactorsByCadNum");
            // verify the required parameter 'dateAppraisal' is set
            if (dateAppraisal == null)
                throw new ApiException(400, "Missing required parameter 'dateAppraisal' when calling RosreestrDataApi->RosreestrDataGetGraphFactorsByCadNum");

            var localVarPath = "/RosreestrData/graph_factors_by_cad_num";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cadNum != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "cad_num", cadNum)); // query parameter
            if (dateAppraisal != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "date_appraisal", dateAppraisal)); // query parameter

            LogContext.PushProperty("DateAppraisal", dateAppraisal);
            LogContext.PushProperty("CadNum", cadNum);
           
            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            //LogContext.PushProperty("Url", localVarResponse.ResponseUri.AbsoluteUri);
            //_log.Debug("RosreestrDataGetGraphFactorsByCadNumWithHttpInfo");
            //_log.ForContext("DateAppraisal", dateAppraisal)
            //    .ForContext("Url", localVarResponse.ResponseUri.AbsoluteUri)
            //    .ForContext("StatusCode", localVarResponse.StatusCode)
            //    .Information("Получение графических факторов по кадастровому номеру {CadNum}", cadNum);

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RosreestrDataGetGraphFactorsByCadNum", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<GraphFactorsData>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (GraphFactorsData)Configuration.ApiClient.Deserialize(localVarResponse, typeof(GraphFactorsData)));
        }

        /// <summary>
        /// Возвращает графические факторы по кадастровому номеру 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="cadNum">Кадастровый номер</param>
        /// <param name="dateAppraisal">Дата оценки</param>
        /// <returns>Task of Object</returns>
        public async System.Threading.Tasks.Task<object> RosreestrDataGetGraphFactorsByCadNumAsync(string cadNum, DateTime? dateAppraisal)
        {
            ApiResponse<object> localVarResponse = await RosreestrDataGetGraphFactorsByCadNumAsyncWithHttpInfo(cadNum, dateAppraisal);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Возвращает графические факторы по кадастровому номеру 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="cadNum">Кадастровый номер</param>
        /// <param name="dateAppraisal">Дата оценки</param>
        /// <returns>Task of ApiResponse (Object)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<object>> RosreestrDataGetGraphFactorsByCadNumAsyncWithHttpInfo(string cadNum, DateTime? dateAppraisal)
        {
            // verify the required parameter 'cadNum' is set
            if (cadNum == null)
                throw new ApiException(400, "Missing required parameter 'cadNum' when calling RosreestrDataApi->RosreestrDataGetGraphFactorsByCadNum");
            // verify the required parameter 'dateAppraisal' is set
            if (dateAppraisal == null)
                throw new ApiException(400, "Missing required parameter 'dateAppraisal' when calling RosreestrDataApi->RosreestrDataGetGraphFactorsByCadNum");

            var localVarPath = "/RosreestrData/graph_factors_by_cad_num";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (cadNum != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "cad_num", cadNum)); // query parameter
            if (dateAppraisal != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "date_appraisal", dateAppraisal)); // query parameter

            LogContext.PushProperty("DateAppraisal", dateAppraisal);
            LogContext.PushProperty("CadNum", cadNum);

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;
            
            //LogContext.PushProperty("Url", localVarResponse.ResponseUri.AbsoluteUri);

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RosreestrDataGetGraphFactorsByCadNum", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<object>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                Configuration.ApiClient.Deserialize(localVarResponse, typeof(object)));
        }

        /// <summary>
        /// Возвращает данные Росреестра по диапазону дат включительно 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dateFrom">Дата с</param>
        /// <param name="dateTo">Дата по</param>
        /// <returns>List&lt;RRDataLoadModel&gt;</returns>
        public List<RRDataLoadModel> RosreestrDataGetRRData(DateTime? dateFrom, DateTime? dateTo)
        {
            ApiResponse<List<RRDataLoadModel>> localVarResponse = RosreestrDataGetRRDataWithHttpInfo(dateFrom, dateTo);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Возвращает данные Росреестра по диапазону дат включительно 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dateFrom">Дата с</param>
        /// <param name="dateTo">Дата по</param>
        /// <returns>ApiResponse of List&lt;RRDataLoadModel&gt;</returns>
        public ApiResponse<List<RRDataLoadModel>> RosreestrDataGetRRDataWithHttpInfo(DateTime? dateFrom, DateTime? dateTo)
        {
            // verify the required parameter 'dateFrom' is set
            if (dateFrom == null)
                throw new ApiException(400, "Missing required parameter 'dateFrom' when calling RosreestrDataApi->RosreestrDataGetRRData");
            // verify the required parameter 'dateTo' is set
            if (dateTo == null)
                throw new ApiException(400, "Missing required parameter 'dateTo' when calling RosreestrDataApi->RosreestrDataGetRRData");

            var localVarPath = "/RosreestrData/xml_by_date";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dateFrom != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "dateFrom", dateFrom)); // query parameter
            if (dateTo != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "dateTo", dateTo)); // query parameter

            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)Configuration.ApiClient.CallApi(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RosreestrDataGetRRData", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<RRDataLoadModel>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<RRDataLoadModel>)Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<RRDataLoadModel>)));
        }

        /// <summary>
        /// Возвращает данные Росреестра по диапазону дат включительно 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dateFrom">Дата с</param>
        /// <param name="dateTo">Дата по</param>
        /// <returns>Task of List&lt;RRDataLoadModel&gt;</returns>
        public async System.Threading.Tasks.Task<List<RRDataLoadModel>> RosreestrDataGetRRDataAsync(DateTime? dateFrom, DateTime? dateTo)
        {
            ApiResponse<List<RRDataLoadModel>> localVarResponse = await RosreestrDataGetRRDataAsyncWithHttpInfo(dateFrom, dateTo);
            return localVarResponse.Data;

        }

        /// <summary>
        /// Возвращает данные Росреестра по диапазону дат включительно 
        /// </summary>
        /// <exception cref="ApiException">Thrown when fails to make API call</exception>
        /// <param name="dateFrom">Дата с</param>
        /// <param name="dateTo">Дата по</param>
        /// <returns>Task of ApiResponse (List&lt;RRDataLoadModel&gt;)</returns>
        public async System.Threading.Tasks.Task<ApiResponse<List<RRDataLoadModel>>> RosreestrDataGetRRDataAsyncWithHttpInfo(DateTime? dateFrom, DateTime? dateTo)
        {
            // verify the required parameter 'dateFrom' is set
            if (dateFrom == null)
                throw new ApiException(400, "Missing required parameter 'dateFrom' when calling RosreestrDataApi->RosreestrDataGetRRData");
            // verify the required parameter 'dateTo' is set
            if (dateTo == null)
                throw new ApiException(400, "Missing required parameter 'dateTo' when calling RosreestrDataApi->RosreestrDataGetRRData");

            var localVarPath = "/RosreestrData/xml_by_date";
            var localVarPathParams = new Dictionary<string, string>();
            var localVarQueryParams = new List<KeyValuePair<string, string>>();
            var localVarHeaderParams = new Dictionary<string, string>(Configuration.DefaultHeader);
            var localVarFormParams = new Dictionary<string, string>();
            var localVarFileParams = new Dictionary<string, FileParameter>();
            object localVarPostBody = null;

            // to determine the Content-Type header
            string[] localVarHttpContentTypes = new string[] {
            };
            string localVarHttpContentType = Configuration.ApiClient.SelectHeaderContentType(localVarHttpContentTypes);

            // to determine the Accept header
            string[] localVarHttpHeaderAccepts = new string[] {
                "application/json",
                "text/json",
                "application/xml",
                "text/xml"
            };
            string localVarHttpHeaderAccept = Configuration.ApiClient.SelectHeaderAccept(localVarHttpHeaderAccepts);
            if (localVarHttpHeaderAccept != null)
                localVarHeaderParams.Add("Accept", localVarHttpHeaderAccept);

            if (dateFrom != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "dateFrom", dateFrom)); // query parameter
            if (dateTo != null) localVarQueryParams.AddRange(Configuration.ApiClient.ParameterToKeyValuePairs("", "dateTo", dateTo)); // query parameter


            // make the HTTP request
            IRestResponse localVarResponse = (IRestResponse)await Configuration.ApiClient.CallApiAsync(localVarPath,
                Method.GET, localVarQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarFileParams,
                localVarPathParams, localVarHttpContentType);

            int localVarStatusCode = (int)localVarResponse.StatusCode;

            if (ExceptionFactory != null)
            {
                Exception exception = ExceptionFactory("RosreestrDataGetRRData", localVarResponse);
                if (exception != null) throw exception;
            }

            return new ApiResponse<List<RRDataLoadModel>>(localVarStatusCode,
                localVarResponse.Headers.ToDictionary(x => x.Name, x => x.Value.ToString()),
                (List<RRDataLoadModel>)Configuration.ApiClient.Deserialize(localVarResponse, typeof(List<RRDataLoadModel>)));
        }

    }
}
